---

name: Production deploy

on:
  push:
    paths:
      - 'Supporting*Resources/v2.0/Datamodel/Datafiles/*.yml'
      - 'Website/**'
    branches:
      - master

jobs:
  deploy-gh:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        name: Download website files
        with:
          name: webpage

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: webpage/Website/public
