name: Generate Web Markdown

on:
  push:
    paths:
      - "Supporting*Resources/v2.0/Datamodel/Datafiles/*.yml"

jobs:
  lintModelv20:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@master
      with:
        file_or_dir: "Supporting*Resources/v2.0/Datamodel/Datafiles/*.yml"
        config_file: .yamllint

  generate-markdown:
    runs-on: ubuntu-18.04
    needs: lintModelv20
    steps:
      - uses: actions/checkout@v2

      - name: "Create output dir and copy files to override spaces in directories"
        run: |
          cp -r Supporting\ Resources/v2.0/Datamodel/Datafiles .
          mkdir output

      - name: "Process datafiles"
        uses: docker://fzipi/owasp-samm-preprocess-yaml:version-0.3.5
        with:
          args: "-d Datafiles -o output"

      - name: "Process artifacts"
        run: |
          mkdir -p business-function/practice/stream
          BASE=output/markdown
          cp "$BASE"/{Design.md,Governance.md,Implementation.md,Operations.md,Verification.md} business-function
          cp "$BASE"/*-??-?.md business-function/practice/stream
          cp "$BASE"/*.md business-function/practice

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v1
        with:
          name: markdown
          path: business-function

  build:
    runs-on: ubuntu-18.04
    needs: generate-markdown
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.3.0
        with:
          hugo-version: '0.59.1'
          extended: true

      - uses: actions/download-artifact@v1
        name: Download markdown-files
        with:
          name: markdown

      - name: Build
        run: |
          find markdown
          cp -r markdown/* Website/content/business-function 
          hugo --gc --minify -v --cleanDestinationDir --environment staging -s Website -d public

      - name: "Upload hugo artifacts"
        uses: actions/upload-artifact@v1
        with:
          name: webpage
          path: Website/public



